# This is a basic workflow to help you get started with Actions

name: Calling

on:
  workflow_dispatch:

jobs:
  calling:
    concurrency: test
    uses: yujincat/yujincat-action/.github/workflows/called.yml@main
