# This is a basic workflow to help you get started with Actions

name: Called

# Controls when the workflow will run
on:
  workflow_call:
  workflow_dispatch:

jobs:
  job1: 
    runs-on: ubuntu-latest
    steps:
      - run: echo evil 
